{{- if not .Values.serviceToken.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "user-persister.fullname" . }}-service-token
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ template "user-persister.name" . }}
    chart: {{ template "user-persister.chart" . }}
    release: {{ template "user-persister.fullname" . }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  token: {{ required "Service token is required" .Values.serviceToken.token | b64enc | quote }}
{{- end }}
