apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "batch-server.fullname" . }}-subscribers-config
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ template "batch-server.name" . }}
    chart: {{ template "batch-server.chart" . }}
    release: {{ template "batch-server.fullname" . }}
    heritage: {{ .Release.Service }}
data:
  subscribers.json: |-
    {{ toJson .Values.subscribers }}

  processors.json: |-
    {{ toJson .Values.processors }}