global:
  image:
    tag: test
    imagePullSecrets:

env:
  gcpEnabled: false
  profile: false
  pubsubEmulatorHost: localenv-pubsub.default.svc.cluster.local:8089
  project: bucketeer-test
  domainTopic: domain
  domainSubscription: push-sender-domain-sub
  pushService: localhost:9001
  featureService: localhost:9001
  maxMps: "1000"
  numWorkers: 2
  pullerNumGoroutines: 5
  pullerMaxOutstandingMessages: "1000"
  pullerMaxOutstandingBytes: "1000000000"
  redis:
    serverName: bucketeer-redis
    poolMaxIdle: 25
    poolMaxActive: 25
    addr: localenv-redis-headless.default.svc.cluster.local:6379
  logLevel: info
  port: 9090
  metricsPort: 9002

tls:
  service:
    secret: bucketeer-service-cert
    cert:
    key:

serviceToken:
  secret:
  token: