global:
  image:
    tag: test
    imagePullSecrets:

env:
  gcpEnabled: false
  profile: false
  pubsubEmulatorHost: localenv-pubsub.default.svc.cluster.local:8089
  project: bucketeer-test
  featureService: localhost:9001
  database: bucketeer
  mysqlUser: bucketeer
  mysqlPass: bucketeer
  mysqlHost: localenv-mysql.default.svc.cluster.local
  mysqlPort: 3306
  mysqlDbName: bucketeer
  maxMps: "1000"
  numWorkers: "2"
  pullerNumGoroutines: "5"
  pullerMaxOutstandingMessages: "1000"
  pullerMaxOutstandingBytes: "1000000000"
  flushInterval: 1m
  logLevel: info
  port: 9090
  metricsPort: 9002
  topic: evaluation
  subscription: evaluation-sub

tls:
  service:
    secret: bucketeer-service-cert
    cert:
    key:

serviceToken:
  secret:
  token:
