global:
  image:
    tag: test
    imagePullSecrets:

env:
  gcpEnabled: false
  profile: false
  pubsubEmulatorHost: localenv-pubsub.default.svc.cluster.local:8089
  project: bucketeer-test
  topic: metrics
  subscription: metrics-sub
  maxMps: "1500"
  numWorkers: 2
  flushSize: 100
  flushInterval: 2s
  pullerNumGoroutines: 5
  pullerMaxOutstandingMessages: "1000"
  pullerMaxOutstandingBytes: "1000000000"
  logLevel: info
  port: 9090
  metricsPort: 9002

tls:
  service:
    secret: bucketeer-service-cert
    cert:
    key:
